kind: Service
apiVersion: v1
metadata:
  name: golang
spec:
  type: LoadBalancer
  selector:
    app: golang
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: golang
  labels:
    app: golang
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8181
